### ISSUE TITLE
Problem with extension

### ISSUE THREAD

**Issue by LuckyDucky123** [FLUORESCENTXX/One-Click-Image-Logger#1]
Once you save it, it becomes a PN file instead of PNG. Yes, I did write image.png and somehow the G is missing.

**Comment by FLUORESCENTXX** [comment]
CTRL + F and select the second one.

**Comment by LuckyDucky123** [comment]
> CTRL + F and select the second one.

Mind dropping your Discord tag? The problem is still there.

**Comment by FLUORESCENTXX** [comment]
fluro#0009
