### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by WppThomas** [FLUORESCENTXX/One-Click-Image-Logger#3]
Im quite confused with the part of hex64 so if you could please help in some way that would be fantastic. thanks!

**Comment by WppThomas** [comment]
Im not quite sure when you say to change it to the picture

**Comment by FLUORESCENTXX** [comment]
It’s literally in the repo

**Comment by FLUORESCENTXX** [comment]
It changes to a picture…

**Comment by WppThomas** [comment]
> It changes to a picture…

sorry im still confused lol. can you please add my discord kiddo#7422 thanks!
